---
template: Hello, !

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors: []

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres